name: Scrape Plans and Upload CSV
on:
  workflow_dispatch: # Allows manual trigger from GitHub UI
jobs:
  scrape_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true   # default true, ensures token available for pushes
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # or your desired version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install firecrawl==0.0.19 pandas pydantic
      - name: Run scraper
        env:
          FIRECRAWL_API_KEY: ${{ secrets.FIRECRAWL_API_KEY2 }}
        run: |
          python scrape_plans.py
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Commit and push CSV if changed
        run: |
          git add plans_output.csv
          # Check if there are changes
          if ! git diff --cached --quiet; then
            git commit -m "Update scraped plans CSV [skip ci]"
            git push origin HEAD:${{ github.ref_name }}
          else
            echo "No changes in plans_output.csv"
          fi
